name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2
        with:
          repository: your-org/backend-repo
          ref: main
          path: backend
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: your-org/backend-repo:latest

  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
        with:
          repository: your-org/frontend-repo
          ref: main
          path: frontend
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: your-org/frontend-repo:latest
